In [1]:
import tensorflow
import numpy as np
mod=tensorflow.keras.models.load_model('data.h5')
def display(img):
    plt.imshow(img[:,:,0])
    plt.set_cmap('gray')
    plt.show()
    
def age_group(age):
    if age >=0 and age < 18:
        return 1
    elif age < 30:
        return 2
    elif age < 80:
        return 3
    else:
        return 4

def get_age(distr):
    distr = distr*4
    if distr >= 0.65 and distr <= 1.4:return "0-18"
    if distr >= 1.65 and distr <= 2.4:return "19-30"
    if distr >= 2.65 and distr <= 3.4:return "31-80"
    if distr >= 3.65 and distr <= 4.4:return "80 +"
    return "Unknown"
    
def get_gender(prob):
    if prob < 0.5:return "Male"
    else: return "Female"

def get_result(sample):
    #print(sample.shape)
    sample = sample/255
    val = mod.predict( np.array([ sample ]) )    
    age = get_age(val[0])
    gender = get_gender(val[1])
    #print("Values:",val,"\nPredicted Gender:",gender,"Predicted Age:",age)
    return gender,age
    

In [4]:
import cv2
cap=cv2.VideoCapture(0)
#mod=tensorflow.keras.models.load_model('saved')
while(True):
    ret,frame=cap.read()
    roi=frame[100:400,320:620]
    #cv2.imshow('roi',roi)
    
    roi=cv2.cvtColor(roi,cv2.COLOR_BGR2GRAY)
    roi=cv2.resize(roi,(64,64),interpolation=cv2.INTER_AREA)
    print(roi)
    
    #cv2.imshow('roi scaled and gray',roi)
    
    copy=frame.copy()
    cv2.rectangle(copy,(250,100),(520,400),(255,0,0),5)
    
    roi=roi.reshape(64,64,1)
    
    gender,age=get_result(roi)
    #if(cv2.waitKey(1)=='r'):
       # print(res)
        
    label="{},{}".format(gender,age)
    
    cv2.putText(copy,label,(220,100),cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),1)
    cv2.imshow('Age and Gender',copy)
    
    if(cv2.waitKey(1)==13):
        break
        
cap.release()
cv2.destroyAllWindows()

[[  6   6   6 ... 184 185 184]
 [  6   6   6 ... 183 184 186]
 [  7   7   7 ... 183 185 187]
 ...
 [  2   2   2 ... 137 136 137]
 [  3   2   3 ... 138 135 136]
 [  2   2   2 ... 137 136 137]]
(64, 64, 1)
[[  5   6   6 ... 181 181 182]
 [  5   6   6 ... 180 181 183]
 [  6   6   6 ... 180 182 182]
 ...
 [  3   2   2 ... 139 139 138]
 [  2   3   2 ... 136 136 138]
 [  2   2   2 ... 137 137 137]]
(64, 64, 1)
[[  5   5   5 ... 180 183 183]
 [  5   5   6 ... 180 181 183]
 [  7   7   7 ... 181 183 182]
 ...
 [  3   2   2 ... 139 138 138]
 [  3   3   2 ... 139 135 137]
 [  2   2   2 ... 138 136 135]]
(64, 64, 1)
[[  6   6   6 ... 182 183 184]
 [  6   7   7 ... 182 185 185]
 [  7   6   7 ... 183 184 185]
 ...
 [  2   2   2 ... 138 140 138]
 [  2   2   2 ... 137 138 136]
 [  2   2   2 ... 135 135 137]]
(64, 64, 1)
[[  6   6   6 ... 181 183 183]
 [  5   6   5 ... 183 183 184]
 [  6   6   6 ... 182 184 185]
 ...
 [  2   2   2 ... 135 135 135]
 [  2   2   2 ... 136 135 133]
 [  2   2   2 ... 136 13